apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: http-ingress
spec:
  rules:
  - host: gmt.test.me
    http:
      paths:
      - path: /
        backend:
          serviceName: blue-green
          servicePort: 8080
